(()=>{const c=window.CHANNEL;if(!c)return;const root=document.documentElement;Object.entries(c.colors).forEach(([k,v])=>root.style.setProperty(`--${k}`,v));document.title=`映像の世界観と編集方法｜${c.name}`;const esc=s=>String(s).replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));const nav=[['premise','1. 読み取った前提'],['decision','2. 今回の判断'],['compare','3. 世界観比較'],['samples','4. 静止画見本'],['stock','5. 素材の役割'],['timelines','6. 60秒構成'],['buy','7. 調達・制作方針'],['open','8. 会議で決めること']];
const styleRows=c.styles.map((s,i)=>`<tr class="${s.recommended?'best':''}"><td><b>${esc(s.id)} ${esc(s.title)}</b>${s.recommended?'<br><span class="pill">主力推薦</span>':''}</td><td>${esc(s.core)}</td><td>${esc(s.strength)}</td><td>${esc(s.readability)}</td><td>${esc(s.continuity)}</td><td>${esc(s.caution)}</td></tr>`).join('');
const galleries=c.styles.map((s,i)=>`<div class="style-head"><div class="style-no">${esc(s.id)}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p></div></div><div class="facts">${s.facts.map(x=>`<div><b>${esc(x[0])}</b>${esc(x[1])}</div>`).join('')}</div><div class="gallery">${s.images.map((src,j)=>`<figure class="shot" data-full="${esc(src)}" tabindex="0" role="button" aria-label="${esc(s.title)}・${esc(c.scenes[j])}を拡大"><img src="${esc(src)}" alt="${esc(s.title)}・${esc(c.scenes[j])}" loading="lazy"><span class="sample-badge">配置見本</span><span class="scene">${j+1} ${esc(c.scenes[j])}</span></figure>`).join('')}</div>`).join('');
const highlights=(c.highlights||[]).length?`<div class="highlights">${c.highlights.map(h=>`<article class="box highlight"><img src="${esc(h.image)}" alt="${esc(h.title)}" loading="lazy"><div><h3>${esc(h.title)}</h3><p>${esc(h.text)}</p><span class="pill">${esc(h.tag)}</span></div></article>`).join('')}</div>`:'';
const timeline=c.timeline.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td>${esc(r[3])}</td><td>${esc(r[4])}</td></tr>`).join('');
const app=document.querySelector('#app');app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="eyebrow">STAFF PROPOSAL</div><h2>目次</h2><nav>${nav.map(n=>`<a href="#${n[0]}">${n[1]}</a>`).join('')}</nav><a class="back" href="../ai-channel-visual-worlds/">← 5チャンネル一覧へ</a></aside><main><header class="hero"><div class="eyebrow">VISUAL DIRECTION & EDITING PLAN · ${esc(c.updated||'2026.09.19')}</div><h1>映像の世界観と<br>編集方法の提案</h1><p>${esc(c.name)}｜${esc(c.tagline)}</p><div class="verdict"><strong>結論：</strong>${c.verdict}</div></header>
<section id="premise"><h2>1. 参照資料から読み取った<span class="marker">確定済み方針</span></h2><p class="lead">${c.premiseLead}</p><div class="two">${c.premise.map(p=>`<div class="box"><h3>${esc(p.title)}</h3><ul>${p.items.map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div><p class="note warn"><strong>今回の試作の扱い：</strong>${c.disclaimer}</p></section>
<section id="decision"><h2>2. 今回の提案で決めること</h2><div class="two"><div class="box rec"><h3>今回の推薦</h3>${c.recommendation}</div><div class="box"><h3>避ける方向</h3><p>${c.avoid}</p></div></div>${highlights}<div class="cinema"><h3>なぜこの作りなのか</h3><p>${c.why}</p><div class="cinema-grid">${c.principles.map(x=>`<div><b>${esc(x[0])}</b>${esc(x[1])}</div>`).join('')}</div></div></section>
<section id="compare"><h2>3. 世界観${c.styles.length}案の比較</h2><div class="table-wrap"><table><thead><tr><th>案</th><th>核になる画</th><th>強み</th><th>見やすさ</th><th>継続性</th><th>主な注意</th></tr></thead><tbody>${styleRows}</tbody></table></div></section>
<section id="samples"><h2>4. 静止画${c.styles.length*4}枚｜同じ4場面で比較</h2><p>画像を押すと拡大します。生成画像内の文字・数字は配置見本です。本番ではPremiere Pro上の統一字幕・検証済み数値へ差し替えます。</p>${galleries}</section>
<section id="stock"><h2>5. 動画・静止画・図解の役割</h2><div class="priority">${c.materials.map((m,i)=>`<div class="box p${i+1}"><h3>${esc(m.title)}</h3><p>${m.text}</p></div>`).join('')}</div><p class="note">${c.ratio}</p></section>
<section id="timelines"><h2>6. 比較用60秒の構成</h2><p>${c.timelineIntro}</p><div class="table-wrap"><table class="timeline"><thead><tr><th>秒数</th><th>役割</th><th>画</th><th>編集</th><th>狙い</th></tr></thead><tbody>${timeline}</tbody></table></div></section>
<section id="buy"><h2>7. 調達・制作方針</h2><div class="priority">${c.buy.map((m,i)=>`<div class="box p${i+1}"><h3>${esc(m.title)}</h3><p>${m.text}</p></div>`).join('')}</div><p class="note warn"><strong>AIの使い所：</strong>${c.ai}</p></section>
<section id="open"><h2>8. ミーティングで決めること</h2><ul class="checklist">${c.questions.map(q=>`<li>${q}</li>`).join('')}</ul><p class="note"><strong>推奨する決め方：</strong>${c.test}</p><div class="channel-switcher"><a href="../ai-channel-visual-style-money/">お金</a><a href="../ai-channel-visual-style-health/">健康</a><a href="../ai-channel-visual-style-spiritual/">スピリチュアル</a><a href="../ai-channel-visual-style-psychology/">心理学</a><a href="../ai-channel-visual-style-hormone/">女性ホルモン</a></div></section><div class="footer">既存企画・映像見本・制作標準を統合したスタッフ比較用資料｜${esc(c.updated||'2026.09.19')}</div></main></div><dialog id="zoom"><button class="close" aria-label="閉じる">×</button><img alt="拡大画像"></dialog>`;
const dialog=document.querySelector('#zoom'),open=f=>{dialog.querySelector('img').src=f.dataset.full;dialog.querySelector('img').alt=f.getAttribute('aria-label');dialog.showModal()};document.querySelectorAll('.shot').forEach(f=>{f.addEventListener('click',()=>open(f));f.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(f)}})});dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});})();
