'use strict';
const G=CampusGrowth;let growth=G.state(),sound=false,motion=true,audioContext;
try{growth=G.state(JSON.parse(localStorage.getItem('plc-growth-v09')||'null'));sound=localStorage.getItem('plc-sound-v09')==='on';motion=localStorage.getItem('plc-motion-v09')!=='off'}catch{}
const memberData={
 'あおい':{c:0,job:'コンテンツホルダー / サポーター',days:186,ltt:1190,t:240,need:'プロデューサーと企画を相談したい',events:[['2026.10.04','成果報告','初めての学習会を開催。参加者の質問を次の教材改善に。','Chatwork・成果報告グループ'],['2026.09.18','やり切った','30日部活で、講座のファネルを完成。','部活動・運営確認'],['2026.08.09','仲間への貢献','初参加メンバーの準備をサポート。','活動シート']]},
 'れん':{c:1,job:'プロデューサー',days:542,ltt:4280,t:360,need:'一緒に講座をつくるコンテンツホルダー募集中',events:[['2026.10.03','成果報告','共同企画を公開。役割分担と学びを仲間に共有。','Chatwork・成果報告グループ'],['2026.09.12','仲間への貢献','ファネル研究の事例をライブラリへ提供。','ナレッジ工房']]},
 'みお':{c:2,job:'ディレクター / 認定講師',days:320,ltt:2750,t:310,need:'ITまわりの相談を受けられます',events:[['2026.10.02','仲間への貢献','ツール活用シェア会を開催。手順書も共有。','イベント・開催記録'],['2026.08.21','成果報告','チームで教材の制作と改善を完了。','Chatwork・成果報告グループ']]},
 'はる':{c:4,job:'サポーター / 運営サポーター',days:92,ltt:780,t:270,need:'新しく入った仲間と一緒に作業したい',events:[['2026.10.05','仲間への貢献','初参加メンバーの作業会をサポート。','イベント・開催記録']]},
 'そう':{c:3,job:'セールス',days:410,ltt:3200,t:180,need:'セールスの経験を共有できます',events:[['2026.09.29','成果報告','相談会で得た改善点と実践結果を報告。','Chatwork・成果報告グループ']]},
 'ゆい':{c:5,job:'コンテンツホルダー',days:65,ltt:530,t:210,need:'企画の壁打ち相手を探しています',events:[['2026.10.01','やり切った','最初の講座アウトラインを完成。','45日シート']]}
};
function ranked(){return G.ranking(Object.entries(memberData).map(([name,p])=>({name,t:name==='あおい'?growth.seasonT:p.t})))}
function chime(win=false){if(!sound)return;try{audioContext||=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const now=audioContext.currentTime;[...(win?[523.25,659.25,783.99]:[523.25,659.25])].forEach((freq,i)=>{const o=audioContext.createOscillator(),v=audioContext.createGain();o.type='sine';o.frequency.value=freq;v.gain.setValueAtTime(0,now+i*.085);v.gain.linearRampToValueAtTime(.045,now+i*.085+.015);v.gain.exponentialRampToValueAtTime(.001,now+i*.085+.18);o.connect(v);v.connect(audioContext.destination);o.start(now+i*.085);o.stop(now+i*.085+.2)})}catch{}}
function settings(){document.body.classList.toggle('motion-off',!motion);$('#motionToggle').setAttribute('aria-pressed',motion);$('#motionToggle').textContent='演出 '+(motion?'ON':'OFF');$('#soundToggle').setAttribute('aria-pressed',sound);$('#soundToggle').textContent='音 '+(sound?'ON':'OFF')}
function updateGrowth(){const lvl=G.level(growth.ltt);$('#myLevel').textContent='Lv.'+lvl;$('#myLtt').textContent=growth.ltt.toLocaleString()+' LTT';$('#xpFill').style.width=(growth.ltt%100)+'%';$('#nextLevel').textContent='次のレベルまで '+(100-growth.ltt%100)+' LTT';$('#mySeason').textContent=growth.seasonT;$('#myRank').textContent=ranked().find(x=>x.name==='あおい').rank+'位';$('#claimReward').textContent=growth.awards.length?'レベルアップ演出をもう一度':'貢献の承認を体験する ＋40';}
const catalogs={
 study:{title:'今日は、どこから学ぼう？',sub:'LEARN SOMETHING. TRY SOMETHING.',copy:'自分のペースで学び、次の実践につなげよう。',cards:[['▤','学習の続きを見る','講座づくりの基本 · 途中から再開','detail:lesson'],['✓','45日シートを進める','目標と、今日の一歩を確認','link:index.html#sheet45'],['☕','学びを仲間に話す','気づきを言葉にする部屋へ','room:learn']]},
 connect:{title:'一緒なら、進められる。',sub:'FIND YOUR PEOPLE.',copy:'作業したい、少し話したい、誰かに聞きたい。',cards:[['◷','一緒にもくもく作業','3人の参加例 · 途中参加も歓迎','room:work'],['☕','ちょっと話す','3人の参加例 · カフェでひと息','room:lounge'],['⌘','ITについて聞く','ツール・連携・設定の相談','room:it'],['↗','PLGについて話す','経験とアイデアを持ち寄る','room:plg']]},
 content:{title:'次の発見が、待っている。',sub:'A LITTLE INSPIRATION.',copy:'動画、実践事例、仲間の知恵から見つけよう。',cards:[['▷','講座づくりの基本','動画の視聴画面を開く','detail:lesson'],['✦','仲間の成果から学ぶ','実践の背景と、積み重ねた道のり','profile:れん'],['▧','教材一覧を見る','テーマからコンテンツを探す','link:index.html#learn']]},
 tools:{title:'どのツールを使おう？',sub:'MAKE GOOD IDEAS HAPPEN.',copy:'やりたいことから選んで、すぐ仕事へ。',cards:[['✧','田中祐一AI','MCPで接続する、あなたの相談相手','detail:ai'],['▣','アド・ファネルライブラリ','参考事例を調べて、知恵をストック','detail:library'],['⌘','みんなのスキル・AI','仲間が共有した仕事の工夫','detail:skills'],['＋','ナレッジを提供する','使える知恵を、みんなの力に','detail:contribute']]}
};
let lastPurpose='tools';
function showActivity(key){lastPurpose=key;const c=catalogs[key];if(!c)return;$('#activityBody').innerHTML=`<p class="eyebrow">${c.sub}</p><h2>${c.title}</h2><p>${c.copy}</p><div class="activity-cards">${c.cards.map(([icon,title,desc,target],i)=>`<button class="floating-card" style="--i:${i}" data-target="${target}"><span class="tile-icon">${icon}</span><b>${title}</b><p>${desc}</p><span class="card-go">開く ↗</span></button>`).join('')}</div><p class="fine">学習・ツール・参加人数は体験用の例です。</p>`;if(!$('#activityDialog').open)$('#activityDialog').showModal();chime()}
function profile(name){const p=memberData[name];if(!p)return;const ltt=name==='あおい'?growth.ltt:p.ltt,t=name==='あおい'?growth.seasonT:p.t;$('#profileBody').innerHTML=`<p class="eyebrow">A PERSON. A STORY. A SHARED FUTURE.</p><div class="profile-hero"><span class="character c${p.c}"></span><div><span class="soft-tag">架空メンバー</span><h2>${name}</h2><p>${p.job}</p><b>Lv.${G.level(ltt)} <small>これまでの成長</small></b></div></div><div class="profile-stats"><div><b>${ltt.toLocaleString()}</b><small>累計 LTT</small></div><div><b>${p.days}日</b><small>在籍日数</small></div><div><b>${t} T</b><small>今期の活動</small></div></div><p class="looking-for">✧ ${p.need}</p><div class="history-heading"><h3>この人が、積み重ねてきたこと。</h3><select id="historyFilter" aria-label="活動履歴の種類"><option value="all">すべての活動</option><option value="成果報告">成果報告</option><option value="仲間への貢献">仲間への貢献</option><option value="やり切った">やり切った</option></select></div><div id="historyList"></div><p class="fine">履歴は架空の例。実装時は承認されたChatworkグループの記録と共通会員IDで紐づけます。個別DMは対象外です。</p><button class="primary" data-profile-talk="${name}">この人と交流する部屋へ</button>`;
 const events=name==='あおい'&&growth.awards.length?[['2026.10.06','仲間への貢献','仕事に使えるナレッジを共有（承認体験）。','この端末のデモ'],...p.events]:p.events;
 const draw=()=>{const list=events.filter(x=>$('#historyFilter').value==='all'||x[1]===$('#historyFilter').value);$('#historyList').innerHTML=list.length?list.map(([date,type,body,source])=>`<article class="timeline-item"><small>${date} · ${type}</small><p>${body}</p><span>${source} · 表示例</span></article>`).join(''):'<p class="fine">この種類の記録はまだありません。</p>'};$('#historyFilter').onchange=draw;draw();if(!$('#profileDialog').open)$('#profileDialog').showModal();chime()}
function seasonBoard(){const list=ranked();$('#activityBody').innerHTML=`<p class="eyebrow">THIS SEASON'S CONTRIBUTORS</p><h2>今、活躍している仲間。</h2><p>2026年10月1日〜12月31日 · 架空の集計例</p><div class="season-note">今期のTポイントだけで順位を集計。<br>累計LTT・レベル・在籍の長さは順位に加えません。</div><div class="leader-list">${list.map(p=>`<button data-person="${p.name}"><span class="rank-no">${p.rank}</span><span class="character c${memberData[p.name].c}"></span><span><b>${p.name}${p.name==='あおい'?'（あなた）':''}</b><small>${memberData[p.name].job}</small></span><strong>${p.t} <small>T</small></strong></button>`).join('')}</div><p class="fine">同点は同順位。順位は今期で切り替わり、過去の成果や累計LTTはプロフィールに残ります。役割・認定は順位で自動付与しません。</p>`;if(!$('#activityDialog').open)$('#activityDialog').showModal();chime()}
function detail(key){const details={ai:['田中祐一AI','ブラウザ内の専用会話画面は設けず、使い慣れたAIクライアントからMCPで利用します。','MCPの接続案内へ','index.html#ai'],library:['アド・ファネルライブラリ','探す → 出典を確認する → 参考事例をストック。共有が承認された貢献をポイントに結びつける設計です。','工房の仲間に相談する','room:ai'],skills:['みんなのスキル・AI','仲間が提供したスキルを、用途・使い方・提供者から選ぶ設計です。実際のライブラリへの接続はこれからです。','工房で相談する','room:ai'],contribute:['あなたの工夫を、みんなの力に。','提供しただけで自動加点せず、出典・利用できる範囲・重複を運営が確認。承認された貢献を高く評価する案です。','工房で共有について話す','room:ai']};
 if(key==='lesson'){$('#activityBody').innerHTML='<p class="eyebrow">LEARN → TRY → SHARE</p><h2>講座づくりの基本</h2><div class="lesson-art"><span>▷</span><b>学んだことが、次の一歩になる。</b></div><p>動画プレーヤーの配置イメージ。ここには実教材を接続していません。</p><div class="season-note">視聴済み区間が70％に達したら一度だけ加点。<br>スキップ・同じ区間の繰り返しは視聴量に重複加算しません。</div><button class="primary" data-target="room:learn">学びとシェアの部屋へ</button><p class="fine">本番はCloudflareの視聴記録と連携。自己申告の完了ボタンでの加点はしません。</p>';return}
 const [title,copy,label,target]=details[key];$('#activityBody').innerHTML=`<p class="eyebrow">YOUR TOOLBOX</p><h2>${title}</h2><div class="tool-orb">✧</div><p>${copy}</p><button class="primary" data-target="${target.startsWith('room:')?target:'link:'+target}">${label} ↗</button><p class="fine">公開デモには実会員データ・実ツールの認証情報を接続していません。</p>`;}
function openRoomFromSheet(id){$('#profileDialog').close();$('#activityDialog').close();if($('#roomDialog').open)$('#roomDialog').close();openRoom(id)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.close)$('#'+b.dataset.close).close();if(b.id==='activityBack')showActivity(lastPurpose);
 if(b.dataset.purpose)showActivity(b.dataset.purpose);
 if(b.dataset.person)profile(b.dataset.person);
 if(b.dataset.profileTalk){const id=Object.keys(rooms).find(k=>rooms[k].people.some(x=>x[0]===b.dataset.profileTalk))||'lounge';openRoomFromSheet(id)}
 if(b.dataset.target){const [type,...rest]=b.dataset.target.split(':'),value=rest.join(':');if(type==='room')openRoomFromSheet(value);if(type==='detail'){detail(value);$('#activityBody').insertAdjacentHTML('beforeend','<button id="activityBack" class="back-to-cards">← メニューに戻る</button>');}if(type==='profile')profile(value);if(type==='link')location.href=value;}
 if(b.id==='myProfile')profile('あおい');if(b.id==='seasonOpen')seasonBoard();
 if(b.id==='soundToggle'){sound=!sound;try{localStorage.setItem('plc-sound-v09',sound?'on':'off')}catch{}settings();chime()}
 if(b.id==='motionToggle'){motion=!motion;try{localStorage.setItem('plc-motion-v09',motion?'on':'off')}catch{}settings()}
 if(b.id==='claimReward'){const replay=!!growth.awards.length,before=12;growth=G.award(growth,{id:'knowledge-approved-demo',season:G.season});try{localStorage.setItem('plc-growth-v09',JSON.stringify(growth))}catch{}updateGrowth();$('#rewardBody').innerHTML=`<p class="eyebrow">YOUR CONTRIBUTION MATTERS</p><div class="level-spark" aria-hidden="true">✦</div><p>${replay?'演出の再生です。ポイントは追加されません。':'仲間へのナレッジ共有が承認されました（体験例）'}</p><h2>LEVEL UP!</h2><div class="level-number">${before} <span>→</span> ${G.level(growth.ltt)}</div><p>あなたの知恵が、みんなの前進に。</p><div class="reward-pills"><span>累計 ＋40 LTT</span><span>今期 ＋40 T</span></div><p class="fine">レベルは累計の成長。順位は今期の活動。<br>実ポイントではなく、この端末だけの体験です。</p><button class="primary" data-close="rewardDialog">キャンパスに戻る</button>`;$('#rewardDialog').showModal();chime(true)}
});
settings();updateGrowth();
