import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
export function campus(el,onRoom){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#e5e7e5');
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','PLCキャンパスの3D。建物をタップすると部屋へ移動します');
 const camera=new THREE.PerspectiveCamera(40,1,.1,200);camera.position.set(15,14,19);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=11;controls.maxDistance=36;controls.minPolarAngle=.2;controls.maxPolarAngle=1.35;controls.target.set(0,0,0);
 scene.add(new THREE.HemisphereLight(0xffffff,0x6c7670,2.5));const light=new THREE.DirectionalLight(0xfff5df,3);light.position.set(-8,18,12);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.camera.left=-16;light.shadow.camera.right=16;light.shadow.camera.top=16;light.shadow.camera.bottom=-16;scene.add(light);
 const world=new THREE.Group();scene.add(world);let targets=[],current='lobby',disposed=false;
 const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.76,...extra});
 function box(w,h,d,x,y,z,c,room){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;if(room){o.userData.room=room;targets.push(o)}world.add(o);return o}
 function label(text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=128;const cx=c.getContext('2d');cx.fillStyle='#ffffff';cx.fillRect(0,0,512,128);cx.fillStyle='#243833';cx.font='bold 36px sans-serif';cx.textAlign='center';cx.fillText(text,256,76);const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,depthTest:false}));sp.position.set(x,y,z);sp.scale.set(3.4,.85,1);world.add(sp)}
 function tree(x,z){box(.14,1.4,.14,x,.7,z,'#8c765c');const o=new THREE.Mesh(new THREE.IcosahedronGeometry(.85,1),mat('#76866a'));o.position.set(x,1.8,z);o.castShadow=true;world.add(o)}
 function clear(){for(const o of [...world.children]){o.traverse(v=>{v.geometry?.dispose();if(v.material){v.material.map?.dispose();v.material.dispose()}});world.remove(o)}targets=[]}
 function build(room='lobby'){current=room;clear();if(room==='lobby'){scene.background.set('#e5e7e5');box(20,.3,16,0,-.25,0,'#c9cdc5');box(2,.02,16,0,-.08,0,'#ece9df');box(20,.02,2,0,-.07,0,'#ece9df');const buildings=[[-5,-4,'learning','LEARNING','#8c9d9d'],[5,-4,'ai','AI CONNECT','#546d75'],[-5,4,'people','COMMUNITY','#b1967d'],[5,4,'profile','MY STUDIO','#7b8877']];for(const [x,z,id,title,c] of buildings){box(5,2.3,3.8,x,1.1,z,'#ece9e0',id);box(5.35,.22,4.2,x,2.4,z,c,id);box(4.5,1.3,.1,x,1.25,z+1.96,'#6e8790',id);box(.1,1.45,.14,x,1.25,z+2.05,'#d9d9cb',id);box(1.2,.14,1,x,.06,z+2.4,'#b7b5a8',id);label(title,x,3.35,z)}for(const [x,z] of [[-8,-6],[8,-6],[-8,6],[8,6],[-1,-6],[1,6]])tree(x,z);const fountain=new THREE.Mesh(new THREE.CylinderGeometry(1.3,1.3,.3,40),mat('#c0cac8'));fountain.position.set(0,.05,0);world.add(fountain);box(.9,.9,.9,0,.55,0,'#a3b9b5');camera.position.set(15,14,19);controls.target.set(0,0,0)}else{const colors={learning:'#e5dfd2',ai:'#d7e3e5',people:'#e8ddd5',profile:'#dfe5d8'};scene.background.set(colors[room]||'#ddd');box(12,.2,9,0,-.2,0,'#c6b59d');box(12,4,.16,0,1.8,-4.5,'#eeeae1');box(.16,4,9,-6,1.8,0,'#e2ded4');box(4,2.1,.12,0,2.1,-4.35,room==='ai'?'#355a66':'#354a45');label(({learning:'LEARNING ROOM',ai:'AI CONNECTION',people:'COMMUNITY LOUNGE',profile:'MEMBER STUDIO'})[room],0,3.7,-4.1);for(let i=0;i<3;i++){let x=(i-1)*3.3;box(2.2,.18,1.3,x,.85,.6,'#f2eee5');for(const dx of [-.85,.85])box(.1,.9,.1,x+dx,.35,.6,'#64706b');box(1,.16,.9,x,.4,2.1,'#778e8c');box(1,.9,.13,x,.85,2.5,'#778e8c')}tree(-4,-3);tree(4,-3);camera.position.set(10,8,12);controls.target.set(0,.8,0)}controls.update();render()}
 function render(){if(!disposed)renderer.render(scene,camera)}
 function size(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();render()}
 controls.addEventListener('change',render);const ro=new ResizeObserver(size);ro.observe(el);let start;
 renderer.domElement.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY]});renderer.domElement.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>8||current!=='lobby')return;const rect=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const h=ray.intersectObjects(targets)[0];if(h)onRoom(h.object.userData.room)});
 build();size();return {room:build,reset:()=>build(current),dispose(){disposed=true;ro.disconnect();controls.dispose();clear();renderer.dispose()}};
}
