import{campus}from'./campus-3d.js';
const $=s=>document.querySelector(s),rooms={learning:{title:'学習ルーム',en:'LEARNING',desc:'動画で学び、実践につなげる',color:'#829897',items:['動画の続きから学ぶ','学びをアウトプットする']},ai:{title:'AI接続ルーム',en:'AI CONNECT',desc:'田中祐一AIとMCPでつながる',color:'#57737c',items:['MCP接続をはじめる','接続状況を確認する']},people:{title:'コミュニティラウンジ',en:'COMMUNITY',desc:'仲間の挑戦や募集を見つける',color:'#b19377',items:['仲間のプロフィールを見る','協力できる人を探す']},profile:{title:'マイスタジオ',en:'MY STUDIO',desc:'あなたの歩みとコレクション',color:'#81916d',items:['活動・在籍の記録を見る','キャラクターを選ぶ']}};
let current='lobby',flat=false,world;const icon='<svg viewBox="0 0 60 45" aria-hidden="true"><path d="M5 18L30 4l25 14M10 18v23h40V18M24 41V25h12v16M15 23h5m20 0h5"/></svg>';
function draw(){document.body.dataset.room=current;$('#place').textContent=current==='lobby'?'キャンパス':rooms[current].title;$('#hint').textContent=current==='lobby'?(flat?'建物をタップして入室できます。':'建物をタップして入室。ドラッグで見回せます。'):'部屋に入りました。下のメニューから次の行動へ。';$('#flat').innerHTML=current==='lobby'?'<div class="map-grid">'+Object.entries(rooms).map(([id,r])=>`<button class="building" data-room="${id}" style="--roof:${r.color}">${icon}<b>${r.title}</b><small>${r.en}</small><span class="enter">入室する ↗</span></button>`).join('')+'</div>':`<div class="room-plan"><div class="screen">${rooms[current].title}</div><div class="desks"><span></span><span></span><span></span></div><p>部屋のメニューは下から選べます ↓</p></div>`;$('#menu').innerHTML=current==='lobby'?'<h2>どこから始めますか？</h2><div class="cards">'+Object.entries(rooms).map(([id,r])=>`<button class="card" data-room="${id}"><small>${r.en}</small><b>${r.title} ↗</b><p>${r.desc}</p></button>`).join('')+'</div>':`<h2>${rooms[current].title}</h2><p>${rooms[current].desc}</p><div class="cards">${rooms[current].items.map(t=>`<a class="card" href="portal-journey.html?room=${current}"><small>PORTAL EXPERIENCE</small><b>${t} ↗</b><p>ポータルのログイン体験から進む</p></a>`).join('')}</div>`;$('#status').textContent=(flat?'2D':'3D')+'表示中';$('#back').disabled=current==='lobby';}
function enter(id){current=id;world?.room(id);draw()}
function view(isFlat){flat=isFlat;$('#world').hidden=flat;$('#flat').hidden=!flat;$('#two').setAttribute('aria-pressed',flat);$('#three').setAttribute('aria-pressed',!flat);$('#camera').hidden=flat;draw()}
try{world=campus($('#world'),enter)}catch{$('#three').disabled=true;view(true);$('#status').textContent='3D非対応のため2D表示'}
$('#two').onclick=()=>view(true);$('#three').onclick=()=>view(false);$('#back').onclick=()=>enter('lobby');$('#camera').onclick=()=>world?.reset();document.addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(b)enter(b.dataset.room)});draw();

const suggestions={new:[['自己紹介を整える','仲間が声をかけやすくするために','10分目安','得意なこと・挑戦したいことを登録','profile'],['最初の学びを始める','まだ学習を始めていない状況の例','15分目安','視聴70％で30点の提案','learning'],['仲間の募集を見てみる','自分の経験が役立つ相手を知るために','5分目安','閲覧だけでは加点しません','people']],club:[['今週の課題を形にする','30日部活動に参加中の状況の例','30分目安','完走100点・完成150点の提案','spec'],['困っている仲間に経験を届ける','同じ活動を進める人の助けになるために','10分目安','具体的な支援の確認で30点の提案','people'],['次のシェア会で話すことを整理する','途中の気づきも、仲間の役に立つために','15分目安','主催・登壇は実施確認後150点の提案','spec']],share:[['成果物を共同ナレッジにする','完成したものを仲間が使える状態にするために','20分目安','スキル・AIの公開採用200点の提案','spec'],['調査をライブラリへ提供する','出典付きの発見を再利用できるために','15分目安','重複のない調査の採用100点の提案','spec'],['使い方をシェアする','使える人を増やし、改善点を集めるために','30分目安','再利用資料の採用100点の提案','spec']]};
function recommend(){const values=suggestions[$('#scenario').value];$('#recommendList').innerHTML=values.map((r,i)=>`<article class="card"><small>${r[2]}</small><b>${r[0]}</b><p>${r[1]}</p><span>${r[3]}</span><a href="${r[4]==='spec'?'journey-spec.html#contribution':'portal-journey.html?room='+r[4]}">${r[4]==='spec'?'活動と評価条件を見る':'この活動へ進む'} ↗</a><button data-dismiss="${i}">今回は見送る</button></article>`).join('')}
$('#scenario').onchange=recommend;document.addEventListener('click',e=>{const b=e.target.closest('[data-dismiss]');if(b){const article=b.closest('article');article.innerHTML='<b>今回は見送りました</b><p>別の活動から進められます。状況を切り替えると体験をやり直せます。</p>'}});recommend();
