'use strict';
const q=s=>document.querySelector(s),html=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sections={home:['⌂','ホーム','あなたの活動と、今日の一歩'],learn:['▤','学ぶ','PLCコンテンツ'],tools:['✧','ツールを探す','PLCツール'],community:['☕','交流する','PLCキャンパス'],support:['♡','サポートを受ける','PLCサポート'],profile:['☺','マイプロフィール','PLCプロフィール'],next:['✓','次にやること','活動ロードマップ']};
let prefs={},profile={name:'あおい',job:'コンテンツホルダー',subjob:'サポーター',intro:'学んだことを形にして、仲間に共有していきたいです。',looking:'プロデューサーと企画を相談したい'},growth=CampusGrowth.state();
try{prefs=JSON.parse(localStorage.getItem('plc-hub-views-v10')||'{}');profile={...profile,...JSON.parse(localStorage.getItem('plc-hub-profile-v10')||'{}')};growth=CampusGrowth.state(JSON.parse(localStorage.getItem('plc-growth-v09')||'null'))}catch{}
const areas={
learn:{en:'THE LEARNING SCHOOL',title:'次の「できた」を、この学校から。',copy:'学びたいテーマの教室へ。続きからでも、気になるところからでも。',places:[['はじめの教室','最初に見るガイド','start','01'],['講座づくりの教室','企画からコンテンツへ','course','02'],['集客・販売の教室','届け方と仕組みづくり','marketing','03'],['実践アーカイブ室','グルコン・ワークショップ','archive','04'],['素材ライブラリー','テンプレート・資料・シート','materials','05']]},
tools:{en:'THE CREATIVE WORKSHOP',title:'仕事が進む、道具に出会う。',copy:'考える、調べる、つくる。目的に合うツールを工房から。',places:[['田中祐一AI','MCPの接続と使い方','ai','01'],['リサーチ工房','アド・ファネルライブラリ','research','02'],['スキルの工房','仲間のAI・スキル','skills','03'],['便利ツール室','日々の実務を助ける','utility','04']]},
community:{en:'THE COMMUNITY CAMPUS',title:'ひとりの一歩を、みんなの前進に。',copy:'一緒に作業する、経験を話す、仲間を探す。',places:[['集まる広場','今いる仲間と作業・会話','rooms','01'],['仲間を探す掲示板','得意なこと・募集から出会う','members','02'],['チームのアトリエ','3ヶ月チーム・30日部活動','teams','03'],['成果のギャラリー','今期の活動・過去の実践','wins','04']]},
support:{en:'THE SUPPORT HOUSE',title:'頼ることも、大切な一歩。',copy:'使えるサポートを確認して、必要な助けへ。',places:[['個別相談室','コンサル・コーチング','consult','01'],['グルコンのホール','参加する・予定を確認する','group','02'],['ワークショップ受付','イベント・シェア会','events','03'],['サポート手帳','利用済み・残り・申請状況','usage','04']]},
profile:{en:'YOUR PERSONAL ATELIER',title:'あなたを知ると、つながりが生まれる。',copy:'写真と分身、ジョブ、成長と実績。自分らしい歩みを育てよう。',places:[['自己紹介のデスク','紹介文・募集ステータス','intro','01'],['ジョブのクローゼット','メイン・サブジョブ','jobs','02'],['歩みのアルバム','成果・貢献・在籍日数','history','03'],['アバターのアトリエ','写真から専用の分身を','avatar','04']]}
};
const rooms={
'learn/start':{title:'はじめの教室',lead:'PLCでの最初の一歩を、ここから。',cards:[['PLCの使い方','活動とサポートの全体像','learn/course/welcome','5分'],['自分の目標を決める','45日シートへつなげる','profile/intro','実践']]},
'learn/course':{title:'講座づくりの教室',lead:'学ぶ → 手を動かす → 仲間に共有する。',cards:[['講座づくりの基本','前回の続き：第2章','learn/course/basics','35% 視聴例'],['企画を言葉にする','誰に、何を届けるか','learn/course/planning','12分の例'],['企画のワークシート','この講座と一緒に使う素材','learn/materials/planning','素材']]},
'learn/marketing':{title:'集客・販売の教室',lead:'届ける相手と、伝える順番を考える。',cards:[['ファネルの基本','全体の流れを学ぶ','learn/course/funnel','動画'],['セールスの準備','相談・提案の組み立て','learn/course/sales','動画'],['実例を調べる','リサーチ工房へ移動','tools/research','ツール']]},
'learn/archive':{title:'実践アーカイブ室',lead:'過去の学びを、今の課題に活かす。',cards:[['グルコンの記録','テーマから振り返る','learn/course/group','アーカイブ'],['ワークショップの記録','実践の手順を見直す','learn/course/workshop','アーカイブ'],['次回の参加を考える','PLCサポートで予定を確認','support/group','サポート']]},
'learn/materials':{title:'素材ライブラリー',lead:'今PLCで使っている素材集の定位置。教材からも、ツールからも同じ素材へ。',cards:[['企画のワークシート','講座を形にするための記入シート','learn/materials/planning','シート'],['発信のテンプレート','学びを自分の言葉にするひな形','learn/materials/post','テンプレート'],['相談準備チェックリスト','相談前に整理しておくこと','learn/materials/consult','資料']]},
 'tools/research':{title:'リサーチ工房',lead:'探す・比較する・ストックするための道具。',cards:[['アド・ファネルライブラリ','競合事例の調査と保存','tools/research/library','接続案内'],['調べ方を学ぶ','先に学習の教室へ','learn/marketing','PLCコンテンツ'],['すぐ使える素材を見る','素材ライブラリーへの共通入口','learn/materials','素材']]},
 'tools/skills':{title:'みんなのスキルの工房',lead:'仲間の工夫を使い、自分の知恵を還元する。',cards:[['スキルを探す','用途と提供者から見つける','tools/skills/catalog','利用'],['スキルを提供する','出典と使い方を添えて申請する','tools/skills/share','貢献']]},
 'tools/utility':{title:'便利ツール室',lead:'実務に使う道具と、記入する素材を使い分ける。',cards:[['45日シート','目標と実践を記録する','tools/utility/sheet','ツール'],['素材ライブラリー','テンプレート・資料を探す','learn/materials','素材']]},
 'community/teams':{title:'チームのアトリエ',lead:'参加に加えて、やり切った成果も残していこう。',cards:[['3ヶ月チーム','共通の目標を持つ仲間と進める','community/teams/quarter','参加状況'],['30日部活動','成果物を完成させる挑戦','community/teams/club','完遂を記録']]},
 'support/consult':{title:'個別相談室',lead:'今の課題に合う支援を選ぶ。',cards:[['コーチング','目標と行動を整理したい','support/consult/coaching','個別'],['セールスコンサル','提案・販売について相談したい','support/consult/sales','個別'],['相談前の準備シート','素材ライブラリーで準備する','learn/materials/consult','素材']]},
 'support/group':{title:'グルコンのホール',lead:'これから参加する場所と、過去の動画を見る場所を分ける。',cards:[['参加の流れを確認','質問を準備して参加する','support/group/join','参加案内'],['過去のグルコンを見る','学ぶ → 実践アーカイブ室へ','learn/archive','動画']]},
 'support/events':{title:'ワークショップ受付',lead:'日程・対象・参加条件を確認してから申し込む。',cards:[['ワークショップ','学びを実践する時間','support/events/workshop','参加案内'],['シェア会','知恵と経験を持ち寄る','support/events/share','交流']]}
};
const labels={};Object.entries(areas).forEach(([k,a])=>a.places.forEach(([title,,id])=>labels[k+'/'+id]=title));Object.values(rooms).forEach(r=>(r.cards||[]).forEach(([title,,path])=>labels[path]||=title));
function link(path,title,cls=''){return `<a class="${cls}" href="#${path}">${title}</a>`}
function cards(list){return `<div class="cards">${list.map(([title,desc,path,badge],i)=>link(path,`<small>${badge||'OPEN'}</small><h3>${title}</h3><p>${desc}</p><span>開く ↗</span>`,'card')).join('')}</div>`}
const areaTheme={learn:{color:'青',tag:'学びを、実践へ。',cta:'コンテンツを開く',image:'learn'},tools:{color:'琥珀',tag:'アイデアを、形に。',cta:'ツールを探す',image:'tools'},community:{color:'緑',tag:'仲間と、前に進む。',cta:'キャンパスへ',image:'community'},support:{color:'珊瑚',tag:'必要なときに、頼れる。',cta:'サポートを確認',image:'support'},profile:{color:'紫',tag:'あなたの歩みが、力になる。',cta:'プロフィールを見る',image:'profile'}};
function pendingFor(key){return quests.filter(x=>x[4].split('/')[0]===key&&x[2]!=='達成')}
function nextLink(key){return `<button class="area-tasks" data-task-area="${key}">${pendingFor(key).length}件の未完了を確認 <span>→</span></button>`}
function home(){return `<section class="portal-hero"><div class="hero-copy"><p class="welcome-line">${html(profile.name)}さん、今日もここから。</p><h1>全員で勝つ</h1><p class="hero-message">学んだことが、自分の力になる。<br>分かち合ったことが、仲間の力になる。</p><div class="hero-actions">${link('learn/course/basics','学習の続きを開く <span>↗</span>','primary')}${link('next','次にやること →','hero-secondary')}</div></div><div class="hero-world"><img src="assets/v11-community-home.jpg" alt="仲間が集まる、緑に囲まれたPLCの広場" fetchpriority="high"><div class="hero-world-caption"><span class="live-dot"></span>いつもの場所で、次の一歩を。</div></div></section><section class="activity-strip" aria-label="自分の活動状況"><div class="activity-self"><span class="account-avatar"></span><span><b>あなたの歩み</b>${link('profile/history','実績を見る →')}</span></div><div><span>成長レベル</span><b>Lv.${CampusGrowth.level(growth.ltt)}</b></div><div><span>累計の貢献</span><b>${growth.ltt.toLocaleString()} <small>LTT</small></b></div><div><span>今期の活動</span><b>${growth.seasonT} <small>T</small></b></div><div><span>PLCと歩んだ時間</span><b>186 <small>日</small></b></div><small class="example-label">活動データは表示例</small></section><section class="section-title"><div><span class="section-kicker">あなたのPLCを使いこなす</span><h2>今日は、どこから始めますか？</h2></div>${link('learn/materials','素材集を開く ↗','text-link')}</section><div class="destination-grid">${Object.entries(areas).map(([key,a])=>`<article class="destination-v11 ${key}">${link(key,`<div class="destination-art"><img src="assets/v11-${key}-card.jpg" alt="${sections[key][2]}の風景" loading="lazy"><span class="place-label">${sections[key][2]}</span></div><div class="destination-copy"><h3>${sections[key][1]}</h3><p>${areaTheme[key].tag}</p><b>${areaTheme[key].cta} ↗</b></div>`)}${nextLink(key)}</article>`).join('')}</div><section class="home-actions"><div class="next-action-panel"><div class="section-title"><div><span class="section-kicker">迷ったら、この一歩から</span><h2>あなたの次にやること</h2></div>${link('next','すべて見る →','text-link')}</div>${quests.filter(x=>x[2]==='進行中'||x[2]==='未着手').slice(0,3).map(([title,cat,status,copy,path])=>link(path,`<span class="task-status">${status}</span><div><b>${title}</b><p>${copy}</p></div><span>↗</span>`,'next-action-row')).join('')}</div><aside class="support-callout"><span class="section-kicker">ひとりで抱え込まない</span><h2>まだ使っていない<br>サポートはありませんか？</h2><p>個別相談、グルコン、ワークショップ。<br>あなたが使える支援を、まとめて確認。</p>${link('support/usage','利用状況を確認する →','primary')}<small>利用枠は体験用の例です。</small></aside></section>`}
function area(key){const a=areas[key],list=prefs[key]==='list';return `<section class="area-hero ${key}"><p class="eyebrow">${a.en}</p><h1>${sections[key][2]}</h1><h2>${a.title}</h2><p>${a.copy}</p></section>${key==='profile'?`<section class="quest-banner"><div><small>YOUR GROWTH</small><h3>Lv.${CampusGrowth.level(growth.ltt)} · ${growth.ltt.toLocaleString()} LTT</h3><p>今期 ${growth.seasonT} T / 在籍186日（例）</p></div>${link('next','次の一歩を見つける ↗','primary')}</section>`:''}<div class="map-bar"><span>行きたい${key==='learn'?'教室':'場所'}を選んでください</span><div role="group" aria-label="表示切替"><button data-view="map" aria-pressed="${!list}">マップ</button><button data-view="list" aria-pressed="${list}">一覧</button></div></div>${list?cards(a.places.map(([t,d,id,n])=>[t,d,key+'/'+id,n])):`<section class="district-map ${key}" aria-label="${sections[key][2]}のマップ"><div class="map-path" aria-hidden="true"></div><div class="district-center"><span>${sections[key][0]}</span><b>${sections[key][2]}</b><small>${a.en}</small></div><div class="map-buildings">${a.places.map(([t,d,id,n],i)=>link(key+'/'+id,`<span class="building" aria-hidden="true"><i></i><em>${n}</em><span>▯ ▯</span></span><b>${t}</b><small>${d}</small>`,'map-place place-'+i)).join('')}</div><p class="map-caption">歩かずに、そのまま入れます。</p></section>`}<section class="area-next-panel"><div><span class="section-kicker">この場所で、次にできること</span><h2>未完了の活動</h2></div>${pendingFor(key).map(([title,cat,status,copy,path])=>link(path,`<span>${status}</span><b>${title}</b><span>取り組む →</span>`,'area-next-row')).join('')||'<p>現在、未完了の活動はありません。</p>'}${nextLink(key)}</section><div class="context-links">${key==='learn'?link('learn/materials','素材集を探す ↗')+link('tools','実践に使うツールへ ↗'):key==='tools'?link('learn/materials','素材集はこちら ↗'):key==='support'?link('learn/archive','過去の動画は「学ぶ」へ ↗'):link('home','活動状況に戻る ↗')}</div>`}
function detailPage(path){if(rooms[path]?.cards)return `<section class="room-heading"><p class="eyebrow">${sections[path.split('/')[0]][2]}</p><h1>${rooms[path].title}</h1><p>${rooms[path].lead}</p></section>${cards(rooms[path].cards)}`;
 if(path==='profile/intro'||path==='profile/jobs')return `<section class="room-heading"><p class="eyebrow">YOUR PERSONAL ATELIER</p><h1>${labels[path]}</h1><p>あなたのことを知ると、声をかけやすくなる。</p></section><form id="profileForm" class="profile-form"><label>呼ばれたい名前<input name="name" maxlength="30" value="${html(profile.name)}" required></label><div class="form-row"><label>メインジョブ<input name="job" maxlength="40" value="${html(profile.job)}"></label><label>サブジョブ<input name="subjob" maxlength="40" value="${html(profile.subjob)}"></label></div><label>自己紹介<textarea name="intro" maxlength="500">${html(profile.intro)}</textarea></label><label>今、探している仲間・できること<input name="looking" maxlength="150" value="${html(profile.looking)}"></label><p class="fine">このブラウザ内のプロフィール例だけを更新します。実会員情報は入力しないでください。</p><button class="primary">プロフィール例を保存する</button></form>`;
 if(path==='profile/history')return `<section class="room-heading"><p class="eyebrow">MY JOURNEY</p><h1>${html(profile.name)}さんの歩み</h1><p>${html(profile.job)} / ${html(profile.subjob)}</p></section><div class="detail-panel"><div class="metric"><b>Lv.${CampusGrowth.level(growth.ltt)}</b><span>${growth.ltt} LTT</span><span>${growth.seasonT} T<small>今期のみ</small></span></div><p>累計の成長と、今期の活動は別の指標です。</p><article class="history"><small>2026.10.04 · 成果報告の例</small><h3>学習会を開催して、次の改善点を共有。</h3><p>出典：指定したChatwork成果報告グループに紐づく表示例</p></article><article class="history"><small>2026.09.18 · 完遂の例</small><h3>30日部活で講座のファネルを完成。</h3><p>出典：部活動の運営確認記録の例</p></article></div>`;
 if(path==='support/usage')return `<section class="room-heading"><p class="eyebrow">YOUR SUPPORT NOTEBOOK</p><h1>使ったサポート、これから使えるサポート。</h1><p>契約に応じた利用枠をここに集約します。以下は架空の例です。</p></section><div class="usage-list"><article><b>個別相談</b><span>利用済み 1回 / 残り 1回</span>${link('support/consult','相談を選ぶ →')}</article><article><b>グルコン</b><span>参加 2回 / アーカイブ視聴 1回</span>${link('support/group','参加の流れ →')}</article><article><b>ワークショップ</b><span>今期は未参加</span>${link('support/events','イベントを見る →')}</article></div>`;
 if(path==='community/rooms')return `<section class="room-heading"><p class="eyebrow">MEET IN THE CAMPUS</p><h1>集まる広場</h1><p>作業・雑談・IT相談など、今やりたいことの部屋へ。</p></section><a class="campus-door" href="park-demo.html?v=10"><div><span>PLC CAMPUS</span><h2>仲間がいる、いつもの場所。</h2><p>参加者を見る・短く話す・Zoomの相談をする</p><b>交流のマップに入る ↗</b></div></a>`;
 if(path==='community/members')return `<section class="room-heading"><p class="eyebrow">FIND YOUR PEOPLE</p><h1>仲間を探す掲示板</h1><p>募集や得意なことから、話してみたい相手を見つける。</p></section>${cards([['れん · プロデューサー','一緒に講座をつくる人を募集中','community/rooms','架空メンバー'],['みお · ディレクター','IT・ツールの相談を受けられます','community/rooms','架空メンバー']])}`;
 if(path==='community/wins')return `<section class="room-heading"><p class="eyebrow">SHARED WINS</p><h1>成果のギャラリー</h1><p>今活躍する仲間と、それぞれの歩みを見る。</p></section>${cards([['今期の活動ランキング','期間内のTポイントで集計。累計とは分離。','community/rooms','10–12月'],['自分の活動履歴','成果・貢献・完遂を振り返る','profile/history','プロフィール']])}<p class="fine">ランキングの操作例は交流マップの「今期の活動」から開けます。</p>`;
 if(path==='profile/avatar')return `<section class="room-heading"><p class="eyebrow">YOUR OWN CHARACTER</p><h1>写真から、あなた専用の分身を。</h1><p>本人の写真から、一人ずつオリジナルを生成。費用はPLC運営が負担します。</p></section><div class="detail-panel"><span class="avatar large"></span><p>このイラストは画風の見本です。写真からの実生成は未接続です。</p><a class="primary" href="park-demo.html?v=10">交流マップで「あなたの分身をつくる」を体験 ↗</a></div>`;
 if(path.startsWith('learn/materials/'))return `<section class="room-heading"><p class="eyebrow">PLC MATERIAL LIBRARY</p><h1>${labels[path]||'学習に使う素材'}</h1><p>素材ライブラリーを正本にして、必要な場所から同じ資料へアクセス。</p></section><div class="material-preview"><small>記入シートの画面例</small><h2>誰の、どんな一歩を助ける？</h2><div>届けたい相手</div><div>その人が目指す状態</div><div>最初に試すこと</div></div><p class="fine">元の素材ファイルは別スレッドの移植対象です。この画面には接続していません。</p><div class="context-links">${link('learn/course','関連する講座へ →')}${link('support/consult','相談で活用する →')}</div>`;
 if(path.startsWith('learn/course/'))return `<section class="room-heading"><p class="eyebrow">LEARN → PRACTICE → SHARE</p><h1>${labels[path]||'PLCの使い方'}</h1></section><div class="lesson-layout"><div class="video-placeholder"><span>▷</span><h2>学びを、次の一歩に。</h2><p>動画プレーヤーの配置例 / 実教材未接続</p></div><aside class="detail-panel"><small>学習の進み具合（例）</small><h2>35%</h2><p>重複を除く視聴区間が70％で、一度だけ加点する設計。</p>${link('learn/materials/planning','この講座の素材を開く ↗','primary')}</aside></div><div class="context-links">${link('community/rooms','学んだことを仲間と話す →')}${link('support/consult','わからないことを相談する →')}</div>`;
 if(path==='tools/ai')return `<section class="room-heading"><p class="eyebrow">TANAKA YUICHI AI</p><h1>田中祐一AI</h1><p>PLCポータルで利用資格と接続を管理し、会話はMCP対応のAIクライアントで。</p></section><div class="detail-panel"><ol><li>PLCポータルにログイン</li><li>対応クライアントから接続を開始</li><li>PLCの画面で接続先と権限を確認</li><li>クライアントに戻って利用</li></ol><p class="fine">接続管理の設計例。実際の認可・接続処理は実行しません。</p><a class="text-link" href="journey-spec.html#auth">ログインと接続の仕様を読む →</a></div>`;
 const title=labels[path]||'参加・利用の案内';return `<section class="room-heading"><p class="eyebrow">YOUR NEXT STEP</p><h1>${title}</h1><p>この画面に、対象・内容・利用条件・次の操作をまとめる設計です。</p></section><div class="detail-panel"><h2>ここで確認できること</h2><p>対象となる会員、使い方や参加の流れ、必要な準備、関連する教材と素材。</p><p class="fine">実データの接続前の動線例です。申込み・予約・ツール実行は行いません。</p>${link(path.startsWith('support/')?'support/usage':'learn/materials',path.startsWith('support/')?'自分の利用状況を見る →':'関連する素材を探す →','primary')}</div>`;
}
let questFilter='残っている',taskArea='all';
const quests=[
 ['はじめの自己紹介を整える','プロフィール','未着手','写真や紹介文、探している仲間を登録。','profile/intro','初回の登録を保存。デモでは実達成判定しません。'],
 ['講座づくりの基本を学ぶ','学ぶ','進行中','現在35％。自分のペースで続きから。','learn/course/basics','重複を除く70％視聴を確認して一度だけ加点。'],
 ['田中祐一AIにつなぐ','ツール','未着手','MCP接続を整え、実践の相談を始める。','tools/ai','初回接続の確認。ログイン回数の水増しは対象外。'],
 ['個別相談を活用する','サポート','未着手','準備シートで課題を整理して相談する。','support/consult','申込みだけでなく、実際の利用を運営が確認。'],
 ['ナレッジを仲間へ届ける','交流・貢献','承認待ち','使える工夫を共有。出典と利用範囲を確認中。','community/rooms','運営承認後に付与。提出だけで自動加点しません。'],
 ['30日部活動をやり切る','交流・実践','達成','講座のファネルを完成させた実績の例。','profile/history','参加と完遂を分けて評価。成果を履歴へ。']
];
function questPage(){const scoped=quests.filter(x=>taskArea==='all'||x[4].split('/')[0]===taskArea),rows=scoped.filter(x=>questFilter==='すべて'||(questFilter==='残っている'?x[2]!=='達成':x[2]===questFilter));return `<section class="room-heading"><p class="eyebrow">YOUR NEXT CHAPTER</p><h1>次にやること</h1><p>あなたがまだ使っていない学びやサポートを、次の一歩に。<br>各エリアで取り組み、達成はプロフィールに積み重なります。</p></section><div class="quest-counts">${['未着手','進行中','承認待ち','達成'].map(status=>`<span><b>${scoped.filter(x=>x[2]===status).length}</b>${status}</span>`).join('')}</div><div class="task-area"><label for="taskArea">取り組む場所</label><select id="taskArea">${[['all','すべての場所'],['learn','学ぶ'],['tools','ツール'],['community','交流'],['support','サポート'],['profile','プロフィール']].map(([v,t])=>`<option value="${v}" ${taskArea===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="quest-filters" role="group" aria-label="活動の状態">${['残っている','未着手','進行中','承認待ち','達成','すべて'].map(v=>`<button data-quest-filter="${v}" aria-pressed="${v===questFilter}">${v}</button>`).join('')}</div><div class="quest-list">${rows.length?'':'<p>この条件で残っている活動はありません。</p>'}${rows.map(([title,cat,status,copy,path,condition])=>`<article class="quest-card"><small>${cat} · ${status}</small><h3>${title}</h3><p>${copy}</p><p class="condition">達成条件：${condition}</p>${link(path,status==='達成'?'実績を見る →':status==='承認待ち'?'共有した場所へ →':'取り組む場所へ ↗')}</article>`).join('')}</div><p class="fine">架空の活動一覧です。今回は表示の絞り込みと動線の体験で、行動完了や承認の同期は未接続です。契約で使えない支援は、本番では利用可能な活動と分けます。</p>`}

function render(){if(!signedIn){renderSignedOut();return;}let path=decodeURIComponent(location.hash.slice(1)||'home').split('?')[0];if(path==='quests')path='next';if(path==='next'){const area=new URLSearchParams(location.hash.split('?')[1]||'').get('area');taskArea=areas[area]?area:'all';}let key=path.split('/')[0];if(!sections[key]){path='home';key='home'}q('#globalNav').innerHTML=Object.entries(sections).map(([id,[icon,title]])=>`<a href="#${id}" ${id===key?'aria-current="page"':''}><span>${title}</span></a>`).join('');const parts=path.split('/');q('#breadcrumbs').innerHTML=link('home','PLCポータル')+(path==='home'?' / ホーム':parts.map((part,i)=>{const target=parts.slice(0,i+1).join('/'),label=i===0?sections[key][1]:labels[target]||'詳細';return ' <span>/</span> '+(i===parts.length-1?`<b aria-current="page">${html(label)}</b>`:link(target,html(label)))}).join(''));q('#view').innerHTML=path==='home'?home():key==='next'?questPage():parts.length===1?area(key):detailPage(path);q('#view').setAttribute('data-section',key);document.body.dataset.area=key==='next'&&taskArea!=='all'?taskArea:key;q('#accountName').textContent=profile.name+'さん';q('#accountButton').setAttribute('aria-label',profile.name+'さんのアカウント');if(q('#taskArea'))q('#taskArea').onchange=e=>{location.hash='next?area='+e.target.value};document.title=(path==='home'?'PLCポータル':(labels[path]||sections[key][1])+' | PLCポータル')+' — 全員で勝つ。';const form=q('#profileForm');if(form)form.onsubmit=e=>{e.preventDefault();const data=new FormData(form);for(const k of ['name','job','subjob','intro','looking'])profile[k]=String(data.get(k)||'').trim();try{localStorage.setItem('plc-hub-profile-v10',JSON.stringify(profile));toast('このブラウザのプロフィール例を保存しました。')}catch{toast('保存できませんでした。入力内容はこの画面に残っています。')}};window.scrollTo({top:0,behavior:'instant'});}
function toast(t){q('#portalToast').textContent=t;q('#portalToast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>q('#portalToast').classList.remove('show'),3000)}
document.addEventListener('click',e=>{if(e.target.closest('#globalNav a')){document.body.classList.remove('nav-open');q('#mobileNavToggle').setAttribute('aria-expanded','false');}const task=e.target.closest('[data-task-area]');if(task){taskArea=task.dataset.taskArea;questFilter='残っている';location.hash='next?area='+taskArea;}const b=e.target.closest('[data-view]');if(e.target.closest('[data-quest-filter]')){questFilter=e.target.closest('[data-quest-filter]').dataset.questFilter;render();}if(b){const key=location.hash.slice(1);prefs[key]=b.dataset.view;try{localStorage.setItem('plc-hub-views-v10',JSON.stringify(prefs))}catch{}render()}});window.addEventListener('hashchange',()=>{document.body.classList.remove('nav-open');q('#mobileNavToggle').setAttribute('aria-expanded','false');q('#accountMenu').hidden=true;q('#accountButton').setAttribute('aria-expanded','false');render()});

let signedIn=true;try{signedIn=sessionStorage.getItem('plc-session-v11')!=='out'}catch{}
function renderSignedOut(){q('#mobileNavToggle').hidden=true;document.body.classList.remove('nav-open');q('#globalNav').hidden=true;q('#breadcrumbs').innerHTML='';q('#accountButton').hidden=true;document.body.dataset.area='home';q('#view').innerHTML=`<section class="login-scene"><div class="login-art"><img src="assets/v11-community-home.jpg" alt="PLCの交流広場"></div><div class="login-copy"><span class="section-kicker">PLCポータル</span><h1>仲間と進む、<br>あなたの場所。</h1><p>ログアウトしました。<br>ここからログイン後の画面を再び体験できます。</p><button class="primary" id="loginButton">体験アカウントでログイン</button><small>本番の認証・MCP接続は操作しません。</small></div></section>`;q('#loginButton').onclick=()=>{signedIn=true;try{sessionStorage.setItem('plc-session-v11','in')}catch{}q('#globalNav').hidden=false;q('#mobileNavToggle').hidden=false;q('#accountButton').hidden=false;location.hash='home';render()};}
q('#mobileNavToggle').onclick=()=>{const open=document.body.classList.toggle('nav-open');q('#mobileNavToggle').setAttribute('aria-expanded',open)};
q('#accountButton').onclick=()=>{const menu=q('#accountMenu');menu.hidden=!menu.hidden;q('#accountButton').setAttribute('aria-expanded',!menu.hidden)};
q('#logoutButton').onclick=()=>{signedIn=false;try{sessionStorage.setItem('plc-session-v11','out')}catch{}q('#accountMenu').hidden=true;q('#accountButton').setAttribute('aria-expanded','false');renderSignedOut()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('nav-open');q('#mobileNavToggle').setAttribute('aria-expanded','false');q('#accountMenu').hidden=true;q('#accountButton').setAttribute('aria-expanded','false')}});
render();
